<!DOCTYPE html>
<html  dir="ltr" lang="pt-br" xml:lang="pt-br">
<head>
    <title>Você Conectado à Ftec em Qualquer Tempo e Lugar</title>
    <link rel="shortcut icon" href="http://graduacao.ftec.com.br/theme/image.php/mjollnir/theme/1380064654/logo" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="moodle, Você Conectado à Ftec em Qualquer Tempo e Lugar" />
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="expires" content="0" />
<link rel="stylesheet" type="text/css" href="http://graduacao.ftec.com.br/theme/yui_combo.php?3.7.3/build/cssreset/reset-min.css&amp;3.7.3/build/cssfonts/fonts-min.css&amp;3.7.3/build/cssgrids/grids-min.css&amp;3.7.3/build/cssbase/base-min.css" /><script type="text/javascript" src="http://graduacao.ftec.com.br/theme/yui_combo.php?3.7.3/build/simpleyui/simpleyui-min.js&amp;3.7.3/build/loader/loader-min.js"></script><script id="firstthemesheet" type="text/css">/** Required in order to fix style inclusion problems in IE with YUI **/</script><link rel="stylesheet" type="text/css" href="http://graduacao.ftec.com.br/theme/styles.php/mjollnir/1380064654/all" />
<script type="text/javascript">
//<![CDATA[
var M = {}; M.yui = {};
var moodleConfigFn = function(me) {var p = me.path, b = me.name.replace(/^moodle-/,'').split('-', 3), n = b.pop();if (/(skin|core)/.test(n)) {n = b.pop();me.type = 'css';};me.path = b.join('-')+'/'+n+'/'+n+'.'+me.type;};
var galleryConfigFn = function(me) {var p = me.path,v=M.yui.galleryversion,f;if(/-(skin|core)/.test(me.name)) {me.type = 'css';p = p.replace(/-(skin|core)/, '').replace(/\.js/, '.css').split('/'), f = p.pop().replace(/(\-(min|debug))/, '');if (/-skin/.test(me.name)) {p.splice(p.length,0,v,'assets','skins','sam', f);} else {p.splice(p.length,0,v,'assets', f);};} else {p = p.split('/'), f = p.pop();p.splice(p.length,0,v, f);};me.path = p.join('/');};
var yui2in3ConfigFn = function(me) {if(/-skin|reset|fonts|grids|base/.test(me.name)){me.type='css';me.path=me.path.replace(/\.js/,'.css');me.path=me.path.replace(/\/yui2-skin/,'/assets/skins/sam/yui2-skin');}};
YUI_config = {"base":"http:\/\/graduacao.ftec.com.br\/lib\/yuilib\/3.7.3\/build\/","comboBase":"http:\/\/graduacao.ftec.com.br\/theme\/yui_combo.php?","combine":true,"filter":"","insertBefore":"firstthemesheet","modules":{"core_filepicker":{"name":"core_filepicker","fullpath":"http:\/\/graduacao.ftec.com.br\/lib\/javascript.php\/1370886509\/repository\/filepicker.js","requires":["base","node","node-event-simulate","json","async-queue","io-base","io-upload-iframe","io-form","yui2-treeview","panel","cookie","datatable","datatable-sort","resize-plugin","dd-plugin","moodle-core_filepicker"]},"core_dock":{"name":"core_dock","fullpath":"http:\/\/graduacao.ftec.com.br\/lib\/javascript.php\/1370886509\/blocks\/dock.js","requires":["base","node","event-custom","event-mouseenter","event-resize"]}},"groups":{"moodle":{"name":"moodle","base":"http:\/\/graduacao.ftec.com.br\/theme\/yui_combo.php?moodle\/1370886509\/","comboBase":"http:\/\/graduacao.ftec.com.br\/theme\/yui_combo.php?","combine":true,"filter":"","ext":false,"root":"moodle\/1370886509\/","patterns":{"moodle-":{"group":"moodle","configFn":moodleConfigFn}}},"local":{"name":"gallery","base":"http:\/\/graduacao.ftec.com.br\/lib\/yui\/gallery\/","comboBase":"http:\/\/graduacao.ftec.com.br\/theme\/yui_combo.php?","combine":true,"filter":"","ext":false,"root":"gallery\/","patterns":{"gallery-":{"group":"gallery","configFn":galleryConfigFn}}},"yui2":{"base":"http:\/\/graduacao.ftec.com.br\/lib\/yuilib\/2in3\/2.9.0\/build\/","comboBase":"http:\/\/graduacao.ftec.com.br\/theme\/yui_combo.php?","combine":true,"ext":false,"root":"2in3\/2.9.0\/build\/","patterns":{"yui2-":{"group":"yui2","configFn":yui2in3ConfigFn}}}}};
M.yui.loader = {modules: {}};
M.cfg = {"wwwroot":"http:\/\/graduacao.ftec.com.br","sesskey":"KIgOkfX4vJ","loadingicon":"http:\/\/graduacao.ftec.com.br\/theme\/image.php\/mjollnir\/core\/1380064654\/i\/loading_small","themerev":"1380064654","slasharguments":1,"theme":"mjollnir","jsrev":"1370886509","svgicons":true};
//]]>
</script>
<script type="text/javascript" src="http://graduacao.ftec.com.br/lib/javascript.php/1370886509/lib/javascript-static.js"></script>
<script type="text/javascript" src="http://graduacao.ftec.com.br/lib/javascript.php/1370886509/lib/analyticsgraduacao.js"></script>
<script type="text/javascript" src="http://graduacao.ftec.com.br/theme/javascript.php/mjollnir/1380064654/head"></script>
    <!-- randomiser for the backgrounds -->
    <style type='text/css'>	html,body { background:#333333 url(http://graduacao.ftec.com.br/theme/image.php/mjollnir/theme/1380064654/landscapebg4) fixed top left no-repeat;}</style>
</head>
<body id="page-site-index" class="course path-site dir-ltr lang-pt_br yui-skin-sam yui3-skin-sam graduacao-ftec-com-br pagelayout-frontpage course-1 context-2 side-pre-only">
<div class="skiplinks"><a class="skip" href="#maincontent">Ir para o conteúdo principal</a></div>
<script type="text/javascript">
//<![CDATA[
document.body.className += ' jsenabled';
//]]>
</script>

<div id="topbars"></div>
<div id="page">
    <!-- MENU TOPO -->
    <div id="menu-header">
    <div id="menu">
        <ul class="menu">
            <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/';return false"><span>&nbsp;&nbsp;In&iacute;cio</span></a></li>
            <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://educacional.ftec.com.br/corpore.net/';return false"><span>&nbsp;&nbsp;Portal</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://ftecvirtual.ftec.com.br/';return false"><span>&nbsp;&nbsp;Rede Social</span></a></li>
            <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://atividades.ftec.com.br/';return false"><span>&nbsp;&nbsp;Atividades Complementares</span></a></li>
            <li><a href="#"><span>&nbsp;&nbsp;Bibliotecas Virtuais</span></a>
                <ul>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://biblioteca.ftec.com.br/';return false"><span>&nbsp;&nbsp;Biblioteca Virtual Pearson</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/course/view.php?id=2120';return false"><span>&nbsp;&nbsp;Bibliotecas Virtuais - Engenharias</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/course/view.php?id=2121';return false"><span>&nbsp;&nbsp;Bibliotecas Virtuais - Gest&atilde;o e Neg&oacute;cios</span></a></li>
					<li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/course/view.php?id=2961';return false"><span>&nbsp;&nbsp;Bibliotecas Virtuais - Inform&aacute;tica</span></a></li>
					<li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/course/view.php?id=2962';return false"><span>&nbsp;&nbsp;Refer&ecirc;ncias Virtuais - Pilotagem</span></a></li>
					<li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/course/view.php?id=2964';return false"><span>&nbsp;&nbsp;Bibliotecas Virtuais - Design</span></a></li>
					<!--
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.escoladegoverno.seap.df.gov.br/index.php?option=com_content&view=article&id=5&Itemid=7';return false"><span>&nbsp;&nbsp;Revista de Gest&atilde;o P&uacute;blica</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://portal.sbc.org.br/bibliotecadigital/';return false"><span>&nbsp;&nbsp;Biblioteca Digital SBC</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.wdl.org/pt/';return false"><span>&nbsp;&nbsp;Biblioteca Digital Mundial</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.periodicos.capes.gov.br/';return false"><span>&nbsp;&nbsp;Portal Peri&oacute;dicos Capes</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.scielo.org/';return false"><span>&nbsp;&nbsp;Biblioteca Virtual - Scielo</span></a></li>                    
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.anpad.org.br/periodicos/content/frame_base.php?revista=1';return false"><span>&nbsp;&nbsp;RAC - Revista de Administra&ccedil;&atilde;o Contempor&acirc;nea</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.rausp.usp.br/';return false"><span>&nbsp;&nbsp;RAUSP - Revista de Administra&ccedil;&atilde;o da USP</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.fgv.br/rae/';return false"><span>&nbsp;&nbsp;RAE - Revista Eletr&ocirc;nica de Administra&ccedil;&atilde;o Facef</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.read.ea.ufrgs.br/';return false"><span>&nbsp;&nbsp;READ - Revista Eletr&otilde;nica de Administra&ccedil;&atilde;o</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.scielo.br/scielo.php?script=sci_issues&pid=1807-7692&lng=en&nrm=isso';return false"><span>&nbsp;&nbsp;BAR - Brazilian Administration Review</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://ebape.fgv.br/publicacoes/rap';return false"><span>&nbsp;&nbsp;Revista de Administra&ccedil;&atilde;o P&uacute;blica</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://seer.ufrgs.br/AnaliseEconomica/issue/archive';return false"><span>&nbsp;&nbsp;Revista An&aacute;lise Econ&ocirc;mica</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.fipe.com.br/publicacoes/ee.asp?codigo=9&versao=p';return false"><span>&nbsp;&nbsp;Revista Estudos Econ&ocirc;micos</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.scielo.br/scielo.php?script=sci_serial&pid=0104-530X&lng=en&nrm=isso';return false"><span>&nbsp;&nbsp;Revista Gest&atilde;o &amp; Produ&ccedil;&atilde;o</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.scielo.br/scielo.php?script=sci_issues&pid=0103-6351&lng=en&nrm=isso';return false"><span>&nbsp;&nbsp;Revista Nova Economia</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.anpocs.org.br/portal/content/blogcategory/13/54/';return false"><span>&nbsp;&nbsp;Revista Brasileira de Ci&ecirc;ncias Sociais</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://bibliotecadigital.fgv.br/ojs/index.php/rbe/issue/archive';return false"><span>&nbsp;&nbsp;Revista Brasileira de Economia</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://revistaproducao.net/index.asp?ss=32&m=1&c=3';return false"><span>&nbsp;&nbsp;Revista Produ&ccedil;&atilde;o</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.seer.ufu.br/index.php/cieng';return false"><span>&nbsp;&nbsp;Revista Ci&ecirc;ncia e Engenharia</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://periodicos.uem.br/ojs/index.php/ActaSciTechnol/index';return false"><span>&nbsp;&nbsp;Revista Acta Scientiarum. Technology</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.set.eesc.usp.br/cadernos/cadernos_det.php?nro=-1';return false"><span>&nbsp;&nbsp;Cadernos de Engenharia de Estruturas</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://periodicos.ufpb.br/ojs2/index.php/juee/about/editorialPolicies#focusAndScope';return false"><span>&nbsp;&nbsp;Journal of Urban and Environmental Engineering</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.scielo.br/scielo.php?script=sci_serial&pid=0370-4467&lng=pt&nrm=iso';return false"><span>&nbsp;&nbsp;REM: Revista Escola de Minas </span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.abcem.org.br/revista-construcao-metalica.php';return false"><span>&nbsp;&nbsp;Constru&ccedil;&atilde;o Met&aacute;lica</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.scielo.br/scielo.php?script=sci_serial&pid=0104-9224&lng=pt&nrm=iso';return false"><span>&nbsp;&nbsp;A Revista Soldagem e Inspe&ccedil;&atilde;o</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.arquitetura.eesc.usp.br/gestaodeprojetos/';return false"><span>&nbsp;&nbsp;Gest&atilde;o e Tecnologia de Projetos</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript:window.location.href='http://www.revistas.uchile.cl/index.php/INVI';return false"><span>&nbsp;&nbsp;Revista INVI</span></a></li>
					-->

                </ul>
            </li>            
            <li><a href="#"><span>&nbsp;&nbsp;Ajuda</span></a>
                <ul>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/public/_modulos/_arquivos/_documentos/calendarioAcademico2012.pdf';return false"><span>&nbsp;&nbsp;Calend&aacute;rio Acad&ecirc;mico 2012</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/public/_modulos/_arquivos/_documentos/manualProfessorMoodle2012.pdf';return false"><span>&nbsp;&nbsp;Manual do Professor Moodle - 2012</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = '';return false"><span>&nbsp;&nbsp;Guia de Aconselhamentos</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = '';return false"><span>&nbsp;&nbsp;Atividades Complementares</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = '';return false"><span>&nbsp;&nbsp;Acesso ao Moodle</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://www.ftec.com.br/alterasenha';return false"><span>&nbsp;&nbsp;Trocar Senha</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = '';return false"><span>&nbsp;&nbsp;EAD - Avalia&ccedil;&otilde;es Presenciais</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = '';return false"><span>&nbsp;&nbsp;EAD - Tutorias Presenciais</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = '';return false"><span>&nbsp;&nbsp;EAD - Professores Online</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = '';return false"><span>&nbsp;&nbsp;Manual Moodle - Professores</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = '';return false"><span>&nbsp;&nbsp;Manual Avalia&ccedil;&atilde;o Institucional</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/index.php?theme=mymobile';return false"><span>&nbsp;&nbsp;Layout Mobile</span></a></li>
                    <!--<li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/index.php?theme=mjollnir';return false"><span>&nbsp;&nbsp;Tema Tradicional</span></a></li> -->
                    <!--<li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://ensino.ftec.com.br/videos/gestao_publica_ead/disciplinasead/';return false"><span>&nbsp;&nbsp;Disciplina EAD - Cursos presencias</span></a></li>-->                    
                    <li></li>
                </ul>
            </li>        
            <li><a href="#"><span>&nbsp;&nbsp;Documentos Institucionais</span></a>
                <ul>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/course/view.php?id=705';return false"><span>&nbsp;&nbsp;Ftec | Caxias do Sul</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/course/view.php?id=706';return false"><span>&nbsp;&nbsp;Ftec | Bento Gon&ccedil;alves</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/course/view.php?id=707';return false"><span>&nbsp;&nbsp;Ftec | Novo Hamburgo</span></a></li>
                    <li><a href="javascript:void(0)" onclick="javascript: window.location.href = 'http://graduacao.ftec.com.br/course/view.php?id=708';return false"><span>&nbsp;&nbsp;Ftec | Porto Alegre</span></a></li>
                </ul>
            </li>
        </ul>
    </div>
    
    </div>
    <!-- MENU TOPO -->
    <div id="page-header">
                <h1 class="headermain">Você Conectado à Ftec em Qualquer Tempo e Lugar</h1>
        
        <div class="headermenu"><div class="logininfo">Você acessou como <a href="http://graduacao.ftec.com.br/user/profile.php?id=3762">Dalmir Antonio da Silva</a> (<a href="http://graduacao.ftec.com.br/login/logout.php?sesskey=KIgOkfX4vJ">Sair</a>)</div>			                                    </div>        <div class="breadcrumb"><span class="accesshide">Caminho da página</span><ul role="navigation"><li><a title="Página inicial" href="http://graduacao.ftec.com.br/">Página inicial</a></li></ul></div>
    </div>
<!-- END OF HEADER -->
    <div id="page-content">
            <!-- START OF PAGE CONTENT -->
		    
		            <div id="region-pre" class="block-region" >
                <div class="region-content">
                    <a href="#sb-1" class="skip-block">Saltar Assista: Mundo Ftec</a><div id="inst10750" class="block_html  block" role="complementary" aria-labelledby="instance-10750-header"><div class="header"><div class="title"><div class="block_action"></div><h2 id="instance-10750-header">Assista: Mundo Ftec</h2></div></div><div class="content"><div class="no-overflow"><p><iframe src="http://player.vimeo.com/video/80632189?title=0&amp;byline=0&amp;portrait=0" frameborder="0" height="142" width="192">Mundo Ftec</iframe></p></div></div></div><span id="sb-1" class="skip-block-to"></span><a href="#sb-2" class="skip-block">Saltar Próximos eventos</a><div id="inst3109" class="block_calendar_upcoming  block" role="complementary" aria-labelledby="instance-3109-header"><div class="header"><div class="title"><div class="block_action"></div><h2 id="instance-3109-header">Próximos eventos</h2></div></div><div class="content"><div class="post">Não há nenhum evento próximo</div><div class="footer"><div class="gotocal"><a href="http://graduacao.ftec.com.br/calendar/view.php?view=upcoming&amp;course=1">Calendário</a>...</div><div class="newevent"><a href="http://graduacao.ftec.com.br/calendar/event.php?action=new&amp;course=1">Novo evento</a>...</div></div></div></div><span id="sb-2" class="skip-block-to"></span><a href="#sb-3" class="skip-block">Saltar Calendário</a><div id="inst3" class="block_calendar_month  block" role="complementary" aria-labelledby="instance-3-header"><div class="header"><div class="title"><div class="block_action"></div><h2 id="instance-3-header">Calendário</h2></div></div><div class="content"><div class="calendar-controls"><a class="arrow_link previous" href="index.php?cal_m=10&amp;cal_y=2013" title="Mês anterior"><span class="arrow ">&#x25C4;</span><span class="accesshide " >&nbsp;<span class="arrow_text">Mês anterior</span></span></a><span class="hide"> | </span><span class="current"><a title="Este mês" href="http://graduacao.ftec.com.br/calendar/view.php?view=month&amp;cal_d=1&amp;cal_m=11&amp;cal_y=2013&amp;course=1">novembro 2013</a></span><span class="hide"> | </span><a class="arrow_link next" href="index.php?cal_m=12&amp;cal_y=2013" title="Próximo mês"><span class="accesshide " ><span class="arrow_text">Próximo mês</span>&nbsp;</span><span class="arrow ">&#x25BA;</span></a><span class="clearer"><!-- --></span>
</div><table class="minicalendar calendartable" summary="novembro 2013 Calendário"><tr class="weekdays"><th scope="col"><abbr title="Domingo">Dom</abbr></th>
<th scope="col"><abbr title="Segunda-feira">Seg</abbr></th>
<th scope="col"><abbr title="Terça-feira">Ter</abbr></th>
<th scope="col"><abbr title="Quarta-feira">Qua</abbr></th>
<th scope="col"><abbr title="Quinta-feira">Qui</abbr></th>
<th scope="col"><abbr title="Sexta-feira">Sex</abbr></th>
<th scope="col"><abbr title="Sábado">Sáb</abbr></th>
</tr><tr><td class="dayblank">&nbsp;</td>
<td class="dayblank">&nbsp;</td>
<td class="dayblank">&nbsp;</td>
<td class="dayblank">&nbsp;</td>
<td class="dayblank">&nbsp;</td>
<td class="day">1</td>
<td class="weekend day">2</td>
</tr><tr><td class="weekend day">3</td>
<td class="day">4</td>
<td class="day">5</td>
<td class="day">6</td>
<td class="day">7</td>
<td class="day">8</td>
<td class="weekend day">9</td>
</tr><tr><td class="weekend day">10</td>
<td class="day">11</td>
<td class="day hasevent calendar_event_course calendar_event_course"><a aria-controls="calendar_tooltip_1_panel" id="calendar_tooltip_1" href="http://graduacao.ftec.com.br/calendar/view.php?view=day&amp;cal_d=12&amp;cal_m=11&amp;cal_y=2013#event_8830">12</a></td>
<td class="day">13</td>
<td class="day">14</td>
<td class="day">15</td>
<td class="weekend day">16</td>
</tr><tr><td class="weekend day">17</td>
<td class="day">18</td>
<td class="day">19</td>
<td class="day">20</td>
<td class="day">21</td>
<td class="day">22</td>
<td class="weekend day">23</td>
</tr><tr><td class="weekend day">24</td>
<td class="day">25</td>
<td class="day hasevent calendar_event_course calendar_event_course"><a aria-controls="calendar_tooltip_2_panel" id="calendar_tooltip_2" href="http://graduacao.ftec.com.br/calendar/view.php?view=day&amp;cal_d=26&amp;cal_m=11&amp;cal_y=2013#event_8844">26</a></td>
<td class="day">27</td>
<td class="day">28</td>
<td class="day hasevent calendar_event_course calendar_event_course"><a aria-controls="calendar_tooltip_3_panel" id="calendar_tooltip_3" href="http://graduacao.ftec.com.br/calendar/view.php?view=day&amp;cal_d=29&amp;cal_m=11&amp;cal_y=2013#event_8845">29</a></td>
<td class="weekend day today eventnone"><span class="accesshide " >Hoje sábado, 30 novembro </span><a aria-controls="calendar_tooltip_4_panel" id="calendar_tooltip_4" href="#">30</a></td>
</tr></table></div></div><span id="sb-3" class="skip-block-to"></span><a href="#sb-4" class="skip-block">Saltar Configurações</a><div id="inst5" class="block_settings  block" role="navigation" aria-labelledby="instance-5-header"><div class="header"><div class="title"><div class="block_action"></div><h2 id="instance-5-header">Configurações</h2></div></div><div class="content"><div id="settingsnav" class="box block_tree_box"><ul class="block_tree list"><li class="type_unknown collapsed contains_branch" aria-expanded="false"><p class="tree_item branch root_node" id="usersettings"><span tabindex="0">Minhas configurações de perfil</span></p><ul><li class="type_setting collapsed item_with_icon"><p class="tree_item leaf"><a title="Modificar perfil" href="http://graduacao.ftec.com.br/user/edit.php?id=3762&amp;course=1"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Modificar perfil</a></p></li>
<li class="type_setting collapsed item_with_icon"><p class="tree_item leaf"><a title="Mudar a senha" href="http://www.ftec.com.br/alterasenha"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Mudar a senha</a></p></li>
<li class="type_setting collapsed item_with_icon"><p class="tree_item leaf"><a title="Chaves de segurança" href="http://graduacao.ftec.com.br/user/managetoken.php?sesskey=KIgOkfX4vJ"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Chaves de segurança</a></p></li>
<li class="type_setting collapsed item_with_icon"><p class="tree_item leaf"><a title="Configuração de Mensagens" href="http://graduacao.ftec.com.br/message/edit.php?id=3762"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Configuração de Mensagens</a></p></li>
<li class="type_unknown collapsed contains_branch" aria-expanded="false"><p class="tree_item branch"><span tabindex="0">Blogs</span></p><ul><li class="type_setting collapsed item_with_icon"><p class="tree_item leaf"><a title="Preferências" href="http://graduacao.ftec.com.br/blog/preferences.php"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Preferências</a></p></li>
<li class="type_setting collapsed item_with_icon"><p class="tree_item leaf"><a title="Blog externo" href="http://graduacao.ftec.com.br/blog/external_blogs.php"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Blog externo</a></p></li>
<li class="type_setting collapsed item_with_icon"><p class="tree_item leaf"><a title="Registrar um blog externo" href="http://graduacao.ftec.com.br/blog/external_blog_edit.php"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Registrar um blog externo</a></p></li></ul></li></ul></li></ul></div></div></div><span id="sb-4" class="skip-block-to"></span><a href="#sb-5" class="skip-block">Saltar Mensagens</a><div id="inst12110" class="block_messages  block" role="complementary" aria-labelledby="instance-12110-header"><div class="header"><div class="title"><div class="block_action"></div><h2 id="instance-12110-header">Mensagens</h2></div></div><div class="content"><div class="info">Não há mensagens pendentes</div><div class="footer"><a href="http://graduacao.ftec.com.br/message/index.php">Mensagens</a></div></div></div><span id="sb-5" class="skip-block-to"></span><a href="#sb-6" class="skip-block">Saltar Navegação</a><div id="inst4" class="block_navigation  block" role="navigation" aria-labelledby="instance-4-header"><div class="header"><div class="title"><div class="block_action"></div><h2 id="instance-4-header">Navegação</h2></div></div><div class="content"><ul class="block_tree list"><li class="type_unknown depth_1 contains_branch current_branch" aria-expanded="true"><p class="tree_item branch active_tree_node canexpand navigation_node"><a title="Página inicial" href="http://graduacao.ftec.com.br/">Página inicial</a></p><ul><li class="type_setting depth_2 item_with_icon"><p class="tree_item leaf hasicon"><a title="Minha página inicial" href="http://graduacao.ftec.com.br/my/"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Minha página inicial</a></p></li>
<li class="type_user depth_2 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch"><span tabindex="0">Meu perfil</span></p><ul><li class="type_custom depth_3 item_with_icon"><p class="tree_item leaf hasicon"><a title="Ver perfil" href="http://graduacao.ftec.com.br/user/profile.php?id=3762"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Ver perfil</a></p></li>
<li class="type_custom depth_3 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch"><span tabindex="0">Mensagens do fórum</span></p><ul><li class="type_custom depth_4 item_with_icon"><p class="tree_item leaf hasicon"><a title="Mensagens" href="http://graduacao.ftec.com.br/mod/forum/user.php?id=3762"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Mensagens</a></p></li>
<li class="type_custom depth_4 item_with_icon"><p class="tree_item leaf hasicon"><a title="Tópicos" href="http://graduacao.ftec.com.br/mod/forum/user.php?id=3762&amp;mode=discussions"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Tópicos</a></p></li></ul></li>
<li class="type_unknown depth_3 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch"><span tabindex="0">Blogs</span></p><ul><li class="type_custom depth_4 item_with_icon"><p class="tree_item leaf hasicon"><a title="Ver todas minhas mensagens" href="http://graduacao.ftec.com.br/blog/index.php?userid=3762"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Ver todas minhas mensagens</a></p></li>
<li class="type_custom depth_4 item_with_icon"><p class="tree_item leaf hasicon"><a title="Acrescentar novo texto" href="http://graduacao.ftec.com.br/blog/edit.php?action=add"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Acrescentar novo texto</a></p></li>
<li class="type_setting depth_4 item_with_icon"><p class="tree_item leaf hasicon"><a title="Blog RSS feed" href="http://graduacao.ftec.com.br/rss/file.php/1/22d653c5ec4fcb28596c1d72bc0789aa/blog/user/3762/rss.xml"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/rss" />Blog RSS feed</a></p></li></ul></li>
<li class="type_setting depth_3 item_with_icon"><p class="tree_item leaf hasicon"><a title="Mensagens" href="http://graduacao.ftec.com.br/message/index.php"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Mensagens</a></p></li>
<li class="type_setting depth_3 item_with_icon"><p class="tree_item leaf hasicon"><a title="Meus arquivos privados" href="http://graduacao.ftec.com.br/user/files.php"><img alt="" class="smallicon navicon" title="" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/i/navigationitem" />Meus arquivos privados</a></p></li></ul></li>
<li class="type_system depth_2 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_1"><a title="Meus cursos" href="http://graduacao.ftec.com.br/my">Meus cursos</a></p></li></ul></li></ul></div></div><span id="sb-6" class="skip-block-to"></span><a href="#sb-7" class="skip-block">Saltar Usuários Online</a><div id="inst10" class="block_online_users  block" role="complementary" aria-labelledby="instance-10-header"><div class="header"><div class="title"><div class="block_action"></div><h2 id="instance-10-header">Usuários Online</h2></div></div><div class="content"><div class="info">(últimos 5 minutos)</div><ul class='list'>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=3762&amp;course=1" title="agora"><img src="http://www.gravatar.com/avatar/7e8a626b71aa46e881bd00c5dde219a1?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />Dalmir Antonio da Silva</a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=4227&amp;course=1" title="6 segundos"><img src="http://www.gravatar.com/avatar/2a4589461b6a375c1c5c6bfb0fa94f00?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />Fabiano Augusto Machado Pinheiro</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=4227" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=4041&amp;course=1" title="26 segundos"><img src="http://www.gravatar.com/avatar/a3955e30772708898776a0ca95901b0a?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />Karen Paola da Silva Plentz</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=4041" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=12158&amp;course=1" title="36 segundos"><img src="http://graduacao.ftec.com.br/pluginfile.php/52121/user/icon/mjollnir/f2?rev=310289" alt="" title="" class="userpicture" width="16" height="16" />Silvia Renata Teles Lopes</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=12158" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=11331&amp;course=1" title="54 segundos"><img src="http://www.gravatar.com/avatar/3cf951da023077bfd313ba143e0e9a15?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />Darlan Martins Maia</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=11331" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=390&amp;course=1" title="1 minuto 13 segundos"><img src="http://www.gravatar.com/avatar/12a76548dc74bc14829666b4365dc119?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />Nataniel Vieira</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=390" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=10880&amp;course=1" title="1 minuto 53 segundos"><img src="http://www.gravatar.com/avatar/2c026b731950b149fba31e7c2a40d525?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />Debora Lidiane Rodrigues Gardini</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=10880" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=4366&amp;course=1" title="1 minuto 56 segundos"><img src="http://www.gravatar.com/avatar/cfdbc895190a843f4a7a576884494674?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />Cristiane Longaray de Oliveira Borba</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=4366" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=8068&amp;course=1" title="2 minutos 21 segundos"><img src="http://www.gravatar.com/avatar/f68cb2fa55567390e00d13c63dcffea8?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />Eduarda Luiza Bertotti</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=8068" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=4225&amp;course=1" title="2 minutos 26 segundos"><img src="http://www.gravatar.com/avatar/37e5657823f2ccd063f6eb25c80449d3?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />Alessandro Schlesner</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=4225" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=16928&amp;course=1" title="2 minutos 32 segundos"><img src="http://www.gravatar.com/avatar/e21c82992e8b7abe39ca8761997a8f60?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />Rubem Daniel Ximenes Oliveira</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=16928" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=8036&amp;course=1" title="2 minutos 39 segundos"><img src="http://graduacao.ftec.com.br/pluginfile.php/16595/user/icon/mjollnir/f2?rev=1" alt="" title="" class="userpicture" width="16" height="16" />Gustavo Chaves</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=8036" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=9153&amp;course=1" title="3 minutos"><img src="http://www.gravatar.com/avatar/00b26ed0597d04b65d335563a6cc907d?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />PABLO SOUZA GRIGOLETTI</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=9153" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=15975&amp;course=1" title="3 minutos 36 segundos"><img src="http://www.gravatar.com/avatar/bb18cfe3a8407ca8cd3a3468e8ec0788?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />PATRICIA RIBEIRO DA SILVA</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=15975" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=13024&amp;course=1" title="4 minutos 16 segundos"><img src="http://graduacao.ftec.com.br/pluginfile.php/74914/user/icon/mjollnir/f2?rev=564794" alt="" title="" class="userpicture" width="16" height="16" />Francele Agostini</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=13024" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=872&amp;course=1" title="5 minutos 6 segundos"><img src="http://graduacao.ftec.com.br/pluginfile.php/902/user/icon/mjollnir/f2?rev=1" alt="" title="" class="userpicture" width="16" height="16" />Daiana Ribas Ribeiro Simão</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=872" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=11352&amp;course=1" title="5 minutos 30 segundos"><img src="http://www.gravatar.com/avatar/8a9a9613bccc360b1238c9126a650107?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />André Luis Bastos da Costa Leite</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=11352" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=17384&amp;course=1" title="5 minutos 30 segundos"><img src="http://www.gravatar.com/avatar/84e34f1dac5058661bcfbf1032b8b944?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />Leandro Pedroni</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=17384" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
<li class="listentry"><div class="user"><a href="http://graduacao.ftec.com.br/user/view.php?id=13085&amp;course=1" title="6 minutos 7 segundos"><img src="http://www.gravatar.com/avatar/4db3fba3e09e411cc38e3b7df3e485dd?s=16&amp;d=mm" alt="" title="" class="userpicture defaultuserpic" width="16" height="16" />Jonathan Silva Dos Santos</a></div><div class="message"><a href="http://graduacao.ftec.com.br/message/index.php?id=13085" title="Enviar uma mensagem"><img class="iconsmall" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/core/1380064654/t/message" alt="Enviar uma mensagem" /></a></div></li>
</ul><div class="clearer"><!-- --></div></div></div><span id="sb-7" class="skip-block-to"></span>                </div>
            </div>
            
        <div id="region-main">
            <div id="contentCol" class="region-content">
                <span id="maincontent"></span><div class="box generalbox sitetopic"><div class="no-overflow"><div id="blocoDestaques">
<ul style="background-color: transparent;"><!--<li style="text-align: center;"><a href="http://agendamentorematricula.ftec.com.br/" target="_blank"><span class="nolink"><img src="http://graduacao.ftec.com.br/pluginfile.php/2/course/section/2/rematriculas2013menor.jpg" alt="CPA" height="142" width="640" /></span></a></li>-->
<li style="text-align: center;"><a href="http://educacional.ftec.com.br" target="_blank"><img src="http://graduacao.ftec.com.br/pluginfile.php/2/course/section/2/Banner_01.jpg" height="187" width="729" /></a></li>
<!--<li style="text-align: center;"><a href="http://www.ftecpolitecnica.com.br" target="_blank"><img src="http://graduacao.ftec.com.br/pluginfile.php/2/course/section/2/politecnica.png" height="210" width="850" /></a></li>-->
<li style="text-align: center;"><a href="http://agendamentorematricula.ftec.com.br" target="_blank"><img src="http://graduacao.ftec.com.br/pluginfile.php/2/course/section/2/rematriculas.png" height="254" width="962" /></a></li>
<!--<li style="text-align: center;"><a href="http://www.ftec.com.br/arquivos/RegulamentoProjetoTV.pdf" target="_blank"> <img src="http://graduacao.ftec.com.br/pluginfile.php/2/course/section/2/Banner%20Eu%20na%20Ftec.jpg" height="144" width="642" /> </a></li>
--></ul>
</div>
<div>
<p></p>
<p>Ftec Caxias do Sul: <a target="_blank" href="http://agendamentorematricula.ftec.com.br">Agendamento de Rematrícula</a></p>
</div></div><ul class="section img-text">
</ul><!--class='section'-->

</div><a href="#skipmycourses" class="skip-block">Saltar meus cursos</a><h2 class="headingblock header">Meus cursos</h2><ul class="unlist"><li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=2980">2013/2 - Ética e Responsabilidade Social EAD - EAD</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=6291&amp;course=1">Márcia Abreu</a></li></ul></div><div class="summary"><div class="enrolmenticons"><img alt="Autoinscrição" class="smallicon" title="Autoinscrição" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/enrol_self/1380064654/withkey" /></div></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=3743">2013/2 - Projeto Empreendedor Ftec-Gestão da Tecnologia da Informação - 420-0033SEXNT - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=9830&amp;course=1">ANDRE LOPES TOCHETTO</a></li></ul></div><div class="summary"><div class="enrolmenticons"><img alt="Autoinscrição" class="smallicon" title="Autoinscrição" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/enrol_self/1380064654/withkey" /></div></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=3539">2013/2 - Gestão do Conhecimento - 430-0030QUINTI1 - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=6233&amp;course=1">ANTONIETA PEPE NAKAMURA</a></li></ul></div><div class="summary"><div class="enrolmenticons"><img alt="Autoinscrição" class="smallicon" title="Autoinscrição" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/enrol_self/1380064654/withkey" /></div></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=3397">2013/2 - Inglês no Contexto Profissional - 420-0005QUINTI2 - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=17803&amp;course=1">LAURA SWIDEREK</a></li></ul></div><div class="summary"><div class="enrolmenticons"><img alt="Autoinscrição" class="smallicon" title="Autoinscrição" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/enrol_self/1380064654/withkey" /></div></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=3338">2013/2 - Comunicação - 430-0001SEGNT - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=6269&amp;course=1">Gilberto Leal da Fonseca</a></li></ul></div><div class="summary"><div class="enrolmenticons"><img alt="Autoinscrição" class="smallicon" title="Autoinscrição" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/enrol_self/1380064654/withkey" /></div></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=3330">2013/2 - Negócios e Comércio Eletrônico - 420-0016TERNTI2 - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=9756&amp;course=1">Marcelo Vasconcellos Benites</a></li></ul></div><div class="summary"><div class="enrolmenticons"><img alt="Autoinscrição" class="smallicon" title="Autoinscrição" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/enrol_self/1380064654/withkey" /></div></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=2133">2013/1 - Ética e Responsabilidade Social EAD - EAD</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=6291&amp;course=1">Márcia Abreu</a></li></ul></div><div class="summary"></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=2828">2013/1 - Empreendedorismo - 430-0004TERMT - Manhã</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=6298&amp;course=1">MARTA MORAES BITENCOURT</a></li></ul></div><div class="summary"><div class="enrolmenticons"><img alt="Autoinscrição" class="smallicon" title="Autoinscrição" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/enrol_self/1380064654/withkey" /></div></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=2846">2013/1 - Engenharia de Software - 420-0019QUANT - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=11131&amp;course=1">Alex Roehrs</a></li></ul></div><div class="summary"></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=2872">2013/1 - Gerência Estratégica da Informação - 420-0018TERNT - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=9151&amp;course=1">FERNANDO ARTMANN</a></li></ul></div><div class="summary"><div class="enrolmenticons"><img alt="Autoinscrição" class="smallicon" title="Autoinscrição" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/enrol_self/1380064654/withkey" /></div></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=2887">2013/1 - Inglês no Contexto Profissional - 420-0005QUINTI2 - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=6288&amp;course=1">MARCELO ALMEIDA CAMARGO PEREIRA</a></li></ul></div><div class="summary"><div class="enrolmenticons"><img alt="Autoinscrição" class="smallicon" title="Autoinscrição" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/enrol_self/1380064654/withkey" /></div></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=2879">2013/1 - Programação Visual - 420-0013SEGNT - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=12103&amp;course=1">Michele Lermen</a></li></ul></div><div class="summary"><div class="enrolmenticons"><img alt="Autoinscrição" class="smallicon" title="Autoinscrição" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/enrol_self/1380064654/withkey" /></div></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=2868">2013/1 - Projeto de Sistemas de Informação - 420-0021SEXNT - Noite</a></h3></div><div class="summary"><div class="enrolmenticons"><img alt="Autoinscrição" class="smallicon" title="Autoinscrição" src="http://graduacao.ftec.com.br/theme/image.php/mjollnir/enrol_self/1380064654/withkey" /></div></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=2803">2013/1 - Sistemas de Informação - 430-0029QUINTI1 - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=6336&amp;course=1">Valter N. Silva</a></li></ul></div><div class="summary"></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=2061">2012/2 - Programação Web - 420-0004SEXNT - Noite</a></h3></div><div class="summary"></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=2047">2012/2 - Programação Visual - 420-0013SEGNT - Noite</a></h3></div><div class="summary"></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=2041">2012/2 - Gestão de Negócios de Tecnologia da Informação - 420-0022QUANT - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=6309&amp;course=1">Paola Carmen Valenzuela Canepa</a></li></ul></div><div class="summary"></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=2034">2012/2 - Sistemas de Informação Inteligentes - 420-0017QUINT - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=9151&amp;course=1">FERNANDO ARTMANN</a></li></ul></div><div class="summary"></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=1940">2012/2 - Gerência de Projetos - 430-0052TERNT - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=6336&amp;course=1">Valter N. Silva</a></li></ul></div><div class="summary"></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=702">2012/1 - Algoritmos e Programação - 420-02SEXMTQUAB - Manhã</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=9151&amp;course=1">FERNANDO ARTMANN</a></li><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=6230&amp;course=1">Aline Duarte Riva</a></li></ul></div><div class="summary"></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=687">2012/1 - Requisitos de Software - 420-0015QUINT - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=9830&amp;course=1">ANDRE LOPES TOCHETTO</a></li></ul></div><div class="summary"></div></div></li>
<li><div class="coursebox clearfix"><div class="info"><h3 class="name"><a title="Clique para entrar neste curso" href="http://graduacao.ftec.com.br/course/view.php?id=668">2012/1 - Segurança em Desenvolvimento de Sistemas da Informação - 420-0020SEXNT - Noite</a></h3><ul class="teachers"><li>Professor: <a href="http://graduacao.ftec.com.br/user/view.php?id=6246&amp;course=1">EDUARDO MOSCHETTA</a></li></ul></div><div class="summary"></div></div></li>
</ul>
<table width="100%"><tr><td align="center"><form id="coursesearch" action="http://graduacao.ftec.com.br/course/search.php" method="get"><fieldset class="coursesearchbox invisiblefieldset"><label for="shortsearchbox">Buscar cursos: </label><input type="text" id="shortsearchbox" size="12" name="search" alt="Buscar cursos" value="" /><input type="submit" value="Vai" /></fieldset></form></td><td align="center"><div class="singlebutton"><form method="get" action="http://graduacao.ftec.com.br/course/index.php"><div><input type="submit" value="Todos os cursos" /></div></form></div></td></tr></table>
<span class="skip-block-to" id="skipmycourses"></span><br />                <div style="clear:both"></div>
            </div>
        </div>
        	<!-- START OF FOOTER -->
		        <div id="page-footer" class="clearfix">
                       <!--<p><img id="institutionalLogo" src="--><!--" alt="Selo" /></p>-->
        </div>
        </div> 					<!-- END OF PAGE CONTENT -->
</div>

<script type="text/javascript" src="http://graduacao.ftec.com.br/theme/javascript.php/mjollnir/1380064654/footer"></script>
<script type="text/javascript">
//<![CDATA[
M.str = {"moodle":{"lastmodified":"\u00daltima atualiza\u00e7\u00e3o","name":"Nome","error":"Erro","info":"Informa\u00e7\u00e3o","viewallcourses":"Ver todos os cursos","cancel":"Cancelar","yes":"Sim"},"repository":{"type":"Tipo","size":"Tamanho","invalidjson":"palavra JSON inv\u00e1lida","nofilesattached":"Nenhum arquivo anexado","filepicker":"File picker","logout":"Sair","nofilesavailable":"Nenhum arquivo dispon\u00edvel","norepositoriesavailable":"Desculpe, nenhum dos seus reposit\u00f3rios atuais pode retornar arquivos no formato solicitado.","fileexistsdialogheader":"Arquivo existe","fileexistsdialog_editor":"Um arquivo com este nome j\u00e1 foi anexado ao texto que voc\u00ea est\u00e1 editando","fileexistsdialog_filemanager":"Um arquivo com este nome j\u00e1 foi anexado","renameto":"Renomear para \"{$a}\"","referencesexist":"H\u00e1 {$a} arquivos pseud\u00f4nimos\/atalhos que usam este arquivo como fonte"},"block":{"addtodock":"Mover isto para a dock","undockitem":"Remover este item do dock","undockall":"Remover todos do dock"},"langconfig":{"thisdirectionvertical":"btt"},"admin":{"confirmation":"Confirma\u00e7\u00e3o"}};
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
var navtreeexpansions4 = [{"id":"expandable_branch_1","key":"mycourses","type":0}];
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
YUI().use('node', function(Y) {
M.util.load_flowplayer();
setTimeout("fix_column_widths()", 20);
M.yui.galleryversion="2010.04.08-12-35";Y.use("moodle-filter_glossary-autolinker",function() {M.filter_glossary.init_filter_autolinking({"courseid":0});
});
Y.use('core_dock', function(Y) { M.core_dock.init_genericblock(Y, "10750"); });
Y.use('core_dock', function(Y) { M.core_dock.init_genericblock(Y, "3109"); });
M.yui.galleryversion="2010.04.08-12-35";Y.use("moodle-calendar-eventmanager",function() {M.core_calendar.add_event({"eventId":"calendar_tooltip_1","title":"ter\u00e7a, 12 novembro eventos","content":"<div><img alt=\"assignment\" class=\"smallicon\" title=\"assignment\" src=\"http:\/\/graduacao.ftec.com.br\/theme\/image.php\/mjollnir\/assignment\/1380064654\/icon\" \/><a href=\"http:\/\/graduacao.ftec.com.br\/calendar\/view.php?view=day&amp;cal_d=12&amp;cal_m=11&amp;cal_y=2013#event_8830\">Resenha Comparativa<\/a><\/div>"});
});
M.yui.galleryversion="2010.04.08-12-35";Y.use("moodle-calendar-eventmanager",function() {M.core_calendar.add_event({"eventId":"calendar_tooltip_2","title":"ter\u00e7a, 26 novembro eventos","content":"<div><img alt=\"assign\" class=\"smallicon\" title=\"assign\" src=\"http:\/\/graduacao.ftec.com.br\/theme\/image.php\/mjollnir\/assign\/1380064654\/icon\" \/><a href=\"http:\/\/graduacao.ftec.com.br\/calendar\/view.php?view=day&amp;cal_d=26&amp;cal_m=11&amp;cal_y=2013#event_9044\">C\u00f3digo de \u00c9tica - Benef\u00edcios e Dificuldades<\/a><\/div><div><img alt=\"assign\" class=\"smallicon\" title=\"assign\" src=\"http:\/\/graduacao.ftec.com.br\/theme\/image.php\/mjollnir\/assign\/1380064654\/icon\" \/><a href=\"http:\/\/graduacao.ftec.com.br\/calendar\/view.php?view=day&amp;cal_d=26&amp;cal_m=11&amp;cal_y=2013#event_8844\">Responsabilidade Social e Meio Ambiente<\/a><\/div>"});
});
M.yui.galleryversion="2010.04.08-12-35";Y.use("moodle-calendar-eventmanager",function() {M.core_calendar.add_event({"eventId":"calendar_tooltip_3","title":"sexta, 29 novembro eventos","content":"<div><img alt=\"assignment\" class=\"smallicon\" title=\"assignment\" src=\"http:\/\/graduacao.ftec.com.br\/theme\/image.php\/mjollnir\/assignment\/1380064654\/icon\" \/><a href=\"http:\/\/graduacao.ftec.com.br\/calendar\/view.php?view=day&amp;cal_d=29&amp;cal_m=11&amp;cal_y=2013#event_9105\">CLIQUE AQUI PARA ENVIAR O TRABALHO EM PDF<\/a><\/div><div><img alt=\"assignment\" class=\"smallicon\" title=\"assignment\" src=\"http:\/\/graduacao.ftec.com.br\/theme\/image.php\/mjollnir\/assignment\/1380064654\/icon\" \/><a href=\"http:\/\/graduacao.ftec.com.br\/calendar\/view.php?view=day&amp;cal_d=29&amp;cal_m=11&amp;cal_y=2013#event_9106\">CLIQUE AQUI PARA ENVIAR O PPT DA APRESENTA\u00c7\u00c3O<\/a><\/div><div><img alt=\"assign\" class=\"smallicon\" title=\"assign\" src=\"http:\/\/graduacao.ftec.com.br\/theme\/image.php\/mjollnir\/assign\/1380064654\/icon\" \/><a href=\"http:\/\/graduacao.ftec.com.br\/calendar\/view.php?view=day&amp;cal_d=29&amp;cal_m=11&amp;cal_y=2013#event_8845\">Responsabilidade e a Micro e Pequena Empresa<\/a><\/div>"});
});
M.yui.galleryversion="2010.04.08-12-35";Y.use("moodle-calendar-eventmanager",function() {M.core_calendar.add_event({"eventId":"calendar_tooltip_4","title":"Hoje s\u00e1bado, 30 novembro","content":"Nenhum evento"});
});
Y.use('core_dock', function(Y) { M.core_dock.init_genericblock(Y, "3"); });
M.yui.galleryversion="2010.04.08-12-35";Y.use("core_dock","moodle-block_navigation-navigation",function() {M.block_navigation.init_add_tree({"id":"5","instance":"5","candock":false});
});
Y.use('core_dock', function(Y) { M.core_dock.init_genericblock(Y, "12110"); });
M.yui.galleryversion="2010.04.08-12-35";Y.use("core_dock","moodle-block_navigation-navigation",function() {M.block_navigation.init_add_tree({"id":"4","instance":"4","candock":false,"courselimit":20,"expansionlimit":"20"});
});
Y.use('core_dock', function(Y) { M.core_dock.init_genericblock(Y, "10"); });
M.util.help_popups.setup(Y);
M.util.init_block_hider(Y, {"id":"inst10750","title":"Assista: Mundo Ftec","preference":"block10750hidden","tooltipVisible":"Esconder o bloco Assista: Mundo Ftec","tooltipHidden":"Mostrar o bloco Assista: Mundo Ftec"});
M.util.init_block_hider(Y, {"id":"inst3109","title":"Pr\u00f3ximos eventos","preference":"block3109hidden","tooltipVisible":"Esconder o bloco Pr\u00f3ximos eventos","tooltipHidden":"Mostrar o bloco Pr\u00f3ximos eventos"});
M.util.init_block_hider(Y, {"id":"inst3","title":"Calend\u00e1rio","preference":"block3hidden","tooltipVisible":"Esconder o bloco Calend\u00e1rio","tooltipHidden":"Mostrar o bloco Calend\u00e1rio"});
M.util.init_block_hider(Y, {"id":"inst5","title":"Configura\u00e7\u00f5es","preference":"block5hidden","tooltipVisible":"Esconder o bloco Configura\u00e7\u00f5es","tooltipHidden":"Mostrar o bloco Configura\u00e7\u00f5es"});
M.util.init_block_hider(Y, {"id":"inst12110","title":"Mensagens","preference":"block12110hidden","tooltipVisible":"Esconder o bloco Mensagens","tooltipHidden":"Mostrar o bloco Mensagens"});
M.util.init_block_hider(Y, {"id":"inst4","title":"Navega\u00e7\u00e3o","preference":"block4hidden","tooltipVisible":"Esconder o bloco Navega\u00e7\u00e3o","tooltipHidden":"Mostrar o bloco Navega\u00e7\u00e3o"});
M.util.init_block_hider(Y, {"id":"inst10","title":"Usu\u00e1rios Online","preference":"block10hidden","tooltipVisible":"Esconder o bloco Usu\u00e1rios Online","tooltipHidden":"Mostrar o bloco Usu\u00e1rios Online"});

});
//]]>
</script>
<!--
<script type="text/javascript">  
    var birdSprite='';  
    var targetElems=new Array('div');  
    var twitterAccount = '@mktftec';  
    var twitterThisText ='';  
    tripleflapInit();  
</script>
-->
</body>
</html>